import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { DiagnosticoReport } from "@/lib/claude-diagnostico";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
    color: "#111827",
  },
  header: {
    marginBottom: 32,
    borderBottom: "2pt solid #0f172a",
    paddingBottom: 16,
  },
  badge: {
    fontSize: 8,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: "#6366f1",
    marginBottom: 8,
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: "#0f172a",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 12,
    color: "#6b7280",
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: "#6366f1",
    marginBottom: 10,
  },
  bodyText: {
    fontSize: 11,
    lineHeight: 1.6,
    color: "#374151",
  },
  listItem: {
    flexDirection: "row",
    marginBottom: 6,
  },
  bullet: {
    fontSize: 11,
    color: "#6366f1",
    marginRight: 8,
    marginTop: 1,
  },
  listText: {
    fontSize: 11,
    lineHeight: 1.5,
    color: "#374151",
    flex: 1,
  },
  tag: {
    backgroundColor: "#f5f3ff",
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 6,
    marginBottom: 6,
  },
  tagText: {
    fontSize: 9,
    color: "#6366f1",
    fontFamily: "Helvetica-Bold",
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  painBox: {
    backgroundColor: "#f5f3ff",
    borderLeft: "3pt solid #6366f1",
    padding: 14,
    borderRadius: 4,
  },
  painText: {
    fontSize: 11,
    lineHeight: 1.6,
    color: "#1e1b4b",
    fontFamily: "Helvetica-Bold",
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    borderTop: "1pt solid #e5e7eb",
    paddingTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 8,
    color: "#9ca3af",
  },
  ctaBox: {
    backgroundColor: "#0f172a",
    padding: 16,
    borderRadius: 4,
    marginTop: 8,
  },
  ctaText: {
    fontSize: 11,
    color: "#ffffff",
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  ctaSub: {
    fontSize: 9,
    color: "#94a3b8",
  },
});

interface Props {
  companyName: string;
  contactName: string;
  report: DiagnosticoReport;
  locale?: string;
}

const t = {
  es: {
    badge: "DIAGNÓSTICO DE AUTOMATIZACIÓN — KAIROS STUDIO",
    generatedBy: "Generado por Kairos Studio",
    processes: "PROCESOS AUTOMATIZABLES IDENTIFICADOS",
    roi: "ROI ESTIMADO",
    stack: "STACK RECOMENDADO",
    nextSteps: "PRÓXIMOS PASOS",
    painPoint: "TU MAYOR OPORTUNIDAD",
    ctaTitle: "¿Listo para implementarlo?",
    ctaSub: "Agenda una llamada con Jhon en calendly.com/jhon-vanegas-506/30min",
  },
  en: {
    badge: "AUTOMATION DIAGNOSIS — KAIROS STUDIO",
    generatedBy: "Generated by Kairos Studio",
    processes: "IDENTIFIED AUTOMATABLE PROCESSES",
    roi: "ESTIMATED ROI",
    stack: "RECOMMENDED STACK",
    nextSteps: "NEXT STEPS",
    painPoint: "YOUR BIGGEST OPPORTUNITY",
    ctaTitle: "Ready to implement it?",
    ctaSub: "Book a call with Jhon at calendly.com/jhon-vanegas-506/30min",
  },
};

export function DiagnosticoPDF({ companyName, contactName, report, locale = "es" }: Props) {
  const labels = locale === "en" ? t.en : t.es;
  const date = new Date().toLocaleDateString(locale === "en" ? "en-US" : "es-CO", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.badge}>{labels.badge}</Text>
          <Text style={styles.title}>{companyName}</Text>
          <Text style={styles.subtitle}>{contactName} · {date}</Text>
        </View>

        {/* Pain point highlight */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.painPoint}</Text>
          <View style={styles.painBox}>
            <Text style={styles.painText}>{report.painPoint}</Text>
          </View>
        </View>

        {/* Summary */}
        <View style={styles.section}>
          <Text style={styles.bodyText}>{report.summary}</Text>
        </View>

        {/* Automatable processes */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.processes}</Text>
          {report.processes.map((p, i) => (
            <View key={i} style={styles.listItem}>
              <Text style={styles.bullet}>✓</Text>
              <Text style={styles.listText}>{p}</Text>
            </View>
          ))}
        </View>

        {/* ROI */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.roi}</Text>
          <Text style={styles.bodyText}>{report.roiEstimate}</Text>
        </View>

        {/* Stack */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.stack}</Text>
          <View style={styles.tagsRow}>
            {report.stack.map((s, i) => (
              <View key={i} style={styles.tag}>
                <Text style={styles.tagText}>{s}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Next steps */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.nextSteps}</Text>
          {report.nextSteps.map((step, i) => (
            <View key={i} style={styles.listItem}>
              <Text style={styles.bullet}>{i + 1}.</Text>
              <Text style={styles.listText}>{step}</Text>
            </View>
          ))}
        </View>

        {/* CTA */}
        <View style={styles.ctaBox}>
          <Text style={styles.ctaText}>{labels.ctaTitle}</Text>
          <Text style={styles.ctaSub}>{labels.ctaSub}</Text>
        </View>

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>{labels.generatedBy} · kairosstudio.vercel.app</Text>
          <Text style={styles.footerText}>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}
